config/routes.rb
MMixProject::Application.routes.draw do

  resources :tournaments

  resources :tracks

  resources :genres

  resources :effects

  resources :effects do
    member do
	    get :download
    end
  end

  devise_for :users do
	get "/", :to => "ppal#index"
  end

	devise_for :users
	resources :users, only: [:show, :index] do
    	resources :posts
	end

root :to => 'ppal#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :user_id, :genre_id, :title, :autor, :tracks

  belongs_to :user and belongs_to :genre
  mount_uploader :tracks, TrackUploader
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.order("updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }

    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
	unless current_user == @effect.user
		redirect_to effects_path
	end 
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])
	@track.user = current_user
	@track.genre_id = params[:genre]

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
   
    unless current_user == @track.user
		redirect_to track_path

	else
	   	@track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
	end
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= simple_form_for(@track) do |f| %>
  	<div class="field">
    	<%= f.input :title %>
	</div>

	<div class="field">
		<%= select("genre", "genre_id", Genre.find(:all).collect {|p| [ p.title, p.id ] }, {:prompt => 'Estilo'})   %>
	</div>

	<div class="file_field">
		<%= f.file_field :tracks %>  
	</div>

  <div class="actions">
    <%= f.submit :subir%>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Últimas pistas agregadas</h1>
<div class="CSSTableGenerator" >
<table>
  <tr>
    <th>Nombre</th>
    <th>Estilo</th>
    <th>Propietario</th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
	<!--td><%= link_to 'Show', track %></td-->
	<td><%= track.title %></td>
	<td><%= track.genre.title %></td>
	<td><%= link_to track.user.email, user_path(track.user) %></td>
	<td><%= link_to 'Ver', track %></td>
    <% if user_signed_in? and current_user == track.user %>
         <td><%= link_to 'Editar', edit_track_path(track) %></td>
         <td><%= link_to 'Eliminar', track, confirm: 'Seguro?', method: :delete %></td>
    <% end %>
<% end %>
</table>
</div>
<br />

<% if user_signed_in? %>
	<%= link_to 'Subir pista nueva', new_track_path %> |
	<%= link_to 'home', root_path %>
<% else %>
    <%= link_to 'home', root_path %>
<% end %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<% if user_signed_in? %>
    autenticado como <%= current_user.email %>.
	    No eres tu?

    <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

<% else %>
        <%= link_to "Regístrate", new_user_registration_path %> or
        <%= link_to "Iniciar Sesión ", new_user_session_path %>
<% end %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
    <%= @track.title %>
</p>

<p>
  <b>Estilo:</b>
    <%= @track.genre.title %>
</p>

<p>
  <b>Propietario</b>
    <%= @track.user.email %>
</p>

<p>
<b>Pista:</b>
   <%= link_to 'Escuchar', "#{@track.tracks}" %> |
</p> 

<% if user_signed_in? and current_user == @track.user%>
	<%= link_to 'Editar', edit_track_path(@track) %> |
<% end %>
	<%= link_to 'Back', tracks_path %>