config/routes.rb
MMixProject::Application.routes.draw do

  resources :tournaments

  resources :tracks

  resources :genres

  resources :effects

  resources :effects do
    member do
	    get :download
    end
  end

  devise_for :users do
	get "/", :to => "ppal#index"
  end

	devise_for :users
	resources :users, only: [:show, :index] do
    	resources :posts
	end

root :to => 'ppal#index'

end

app/models/effect.rb
class Effect < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :efx

  belongs_to :user
  mount_uploader :efx, EfxUploader
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  # GET /effects
  # GET /effects.json
  def index
    @effects = Effect.order("updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @effects }
    end
  end

  # GET /effects/1
  # GET /effects/1.json
  def show
    @effect = Effect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @effect }
    end
  end

  def download
      @effect = Effect.find(params[:id])
	  send_file @effect.efx, :type=>"audio/mp3", :disposition => :attachment
  end

  # GET /effects/new
  # GET /effects/new.json
  def new
    @effect = Effect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/1/edit
  def edit
    @effect = Effect.find(params[:id])
	unless current_user == @effect.user
	    redirect_to effects_path
	end
  end

  # POST /effects
  # POST /effects.json
  def create
    @effect = Effect.new(params[:effect])
	
		@effect.user=current_user

    respond_to do |format|
      if @effect.save
        format.html { redirect_to @effect, notice: 'Effect was successfully created.' }
        format.json { render json: @effect, status: :created, location: @effect }
      else
        format.html { render action: "new" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /effects/1
  # PUT /effects/1.json
  def update
 	@effect = Effect.find(params[:id])

    respond_to do |format|
      if @effect.update_attributes(params[:effect])
        format.html { redirect_to @effect, notice: 'Effect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /effects/1
  # DELETE /effects/1.json
  def destroy
    @effect = Effect.find(params[:id])

	unless current_user == @effect.user
	    redirect_to effects_path

	else
		@effect.destroy

    respond_to do |format|
      format.html { redirect_to effects_url }
      format.json { head :no_content }
    end
    end
  end

end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/views/effects/_form.html.erb
<%= simple_form_for @effect, :html => {:multipart => true} do |f| %>
	<div class="field">
    	<%= f.input :title %>
	</div>

	<div class="field">
		<%= f.input :content, :input_html => {:size => "30x3"} %>
	</div>

	<div class="file_field">
		<%= f.file_field :efx %>  
	</div>

	<div class="actions">
		<%= f.submit :subir %>
	</div>

<% end %>

app/views/effects/edit.html.erb
<h1>Editamdo efecto</h1>

<%= render 'form' %>

<%= link_to 'Ver', @effect %> |
<%= link_to 'Volver', effects_path %> |
<%= link_to 'ir a principal', root_path %>

app/views/effects/index.html.erb
<h1>Lista de efectos</h1>
<div class="CSSTableGenerator" >
<table>
  <tr>
    <th>Nombre</th>
    <th>Comentario</th>
    <th>Propietario</th>
  </tr>

<% @effects.each do |effect| %>
  <tr>
    <!--td><%= link_to 'Show', effect %></td-->
	<td><%= effect.title %></td>
    <td><%= effect.content %></td>
    <td><%= link_to effect.user.email, user_path(effect.user) %></td>
  	<td><%= link_to 'Ver', effect %></td>
	<% if user_signed_in? and current_user == effect.user %>
    	<td><%= link_to 'Editar', edit_effect_path(effect) %></td>
 	    <td><%= link_to 'Eliminar', effect, confirm: 'Seguro?', method: :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>
<br />
</div>
<% if user_signed_in? %>
	<%= link_to 'Subir efecto nuevo', new_effect_path %> |
	<%= link_to 'home', root_path %>
<% else %>
	<%= link_to 'home', root_path %>
<% end %>

app/views/effects/new.html.erb
<h1>Agregar nuevo efecto</h1>

<% if user_signed_in? %>
    autenticado como <%= current_user.email %>.
	    No eres tu?

    <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>

<%= render 'form' %>

<%= link_to 'Back', effects_path %>

<% else %>
        <%= link_to "Regístrate", new_user_registration_path %> or
        <%= link_to "Iniciar Sesión ", new_user_session_path %>
<% end %>

app/views/effects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
    <%= @effect.title %>
</p>

<p>
  <b>Content:</b>
    <%= @effect.content %>
</p>

<p>
  <b>User:</b>
    <%= @effect.user.email %>
</p>

 <p>
<b>efx:</b>
   <%= link_to 'Escuchar', "#{@effect.efx}" %> |
   <%= link_to "Descargar", :action =>'download', :controller =>'effects',:id => @effect %>
</p>

<% if user_signed_in? and current_user == @effect.user%>
	<%= link_to 'Editar', edit_effect_path(@effect) %> |
<% end %>
	<%= link_to 'Back', effects_path %>