config/routes.rb
MMixProject::Application.routes.draw do

  resources :tournaments

  resources :tracks

  resources :genres

  resources :effects

  resources :effects do
    member do
	    get :download
    end
  end

  devise_for :users do
	get "/", :to => "ppal#index"
  end

	devise_for :users
	resources :users, only: [:show, :index] do
    	resources :posts
	end

root :to => 'ppal#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :about
  # attr_accessible :title, :body

  has_many :effects and has_many :tracks

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		@users = User.all(:order => "created_at ASC")
    end

	def show
	    @user = User.find(params[:id])
		@effects = Effect.where(:user_id => @user.id).order("updated_at desc")
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
  <tr>
	<td><%= link_to user.email, user_path(user) %></td><br><br>
  </tr>
<% end %>

app/views/user/show.html.erb
<h1>Perfil de Usuario</h1>
<!--p>Find me in app/views/users/show.html.erb</p-->
	<%= link_to 'efectos', effects_path %> |
    <%= link_to 'ppal', ppal_index_path %>
<hr>
	<h2>Informacion de usuario</h2>
	<tr>
		<br><br>
		<td><%= @user.email %></td><br>
		<td><%= @user.about %></td><br>
    </tr>
<% if user_signed_in? and current_user == @user %>
	<%= link_to 'Editar perfil', edit_user_registration_path %>
<% end %>

<h2> Efectos subidos </h2>
	<% @effects.each do |effect| %>
	<tr>
		<td><%= effect.title %></td><br>
		<td><%= effect.content %></td><br>
		<td><%= effect.created_at %></td><br>
		<td><%= effect.updated_at %></td><br><br>
    </tr>
	<% end %>